var arcano = [{
        img: '<img src="../img/cartas/maiores/00.jpg">',
        numero: '0 | 22',
        nome: 'O Louco',
        verbo: 'Ousar',
        chaves: 'Inocência, Novos começos, Espírito livre',
        hebraico: "Aleph",
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: '<b>Hajo Bhanzaf:</b> Potencial original, caos criativo, despreocupação. novo' +
            'começo, partida para desconhecido, liberdade concedida pela loucura. leviandade. ',
        material: '<b>Hajo Bhanzaf</b> Começar do zero, brincar com as mais diversas possibilidades, pausa produtiva, estar aberto para novas atividades, inexperiência' +
            'profissional, planos caóticos, falta de responsabilidade.',
        mental: '<b>Hajo Bhanzaf:</b> Tornar-se consciente da abundância quase ilimitada de' +
            'suas possibilidades, fazer um <i>brainstorming</i>. ',
        sentimental: '<b>Hajo Bhanzaf:</b> Vontade de curtir a vida, descontração, paquera, convivência' +
            'afetuosa, encontro novo e revigorante, relacionamento aberto, experimentar. ',
        espiritual: false,
        conselho: '<b>Hajo Bhanzaf:</b> Experimentar algo novo de uma forma descontraída e divertida. ',
        advertencia: '<b>Hajo Bhanzaf:</b> Circunstâncias caóticas e frivolidade exacerbada. ',
        cartaDoDia: 'Você deve hoje estar aberto a tudo. Passe dia da forma' +
            'mais descontraída possível, não leve nada muito a sério e encare até os "acontecimentos' +
            'mais insólitos" com uma divertida curiosidade. Quanto menos você se prender a idéias' +
            'às quais está habituado e às experiências já testadas e comprovadas, mais excitante e' +
            'incomum será seu dia. Caso chegue à conclusão de ter hoje de recomeçar um' +
            'determinado assunto do zero, então ouse um começo incomum, mais' +
            'despreocupadamente possível. Permita-se, ao menos uma vez, um pouco de "loucura"! ',
    },
    {
        img: '<img src="../img/cartas/maiores/01.jpg">',
        numero: 'I',
        nome: 'O Mago',
        verbo: 'Criar',
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/02.jpg">',
        numero: 'II',
        nome: 'A Alta Sacerdotiza',
        verbo: 'Analizar',
        chaves: 'Intuição, Inconsciente, Voz Interior, Paciência, Reserva, Resignação',
        hebraico: 'Gimmel',
        astrologia: 'A Lua - Inconsciente, ânimo, premonição, sonho, sagacidade',
        simbologia: 'A Mãe celestial, a donzela. Simboliza o ato de analizar e esperar pela hora certa de agir ',
        aspectos: '**Guia interior, sabedoria, intuição feminina, visões, fantasia, mistério, disposição passiva, ser guiado.',
        geral: 'A Sacerdotisa protege o portal do templo sagrado da alma humana, só permitirá a entrada de quem souber decifrar seu enigma: fidelidade e integridade. Esse  conjunto simbólico sugere que há uma grande força pessoal retida e que não será revelada facilmente, há um desejo passivo e muita elucubração. A análise e a intuição são por demais profundas nos fatores envolvidos, a busca do conhecimento é pela perfeição, os projetos e as relações são as mais passivas e corretas possíveis. A PAPISA representa nossas habilidades desconhecidas, nossa sensibilidade, nossa intenção e uma confiança inexplicável mas profundamente enraizada. Ela é a chave para a verdade misteriosa que foge à nossa compreensão lógica. Ela sabe que a verdade que pode ser expressa não é a verdade eterna. Seu lado luminoso é a expressão da paciência, da compreensão, da indulgência, da bondade, da disposição para perdoar e utilizar o poder das forças inconscientes para o bem dos outros - como auxiliadora, curadora ou vidente. Mas seu lado sombrio corresponde ao arquétipo da "irmã negra", a feiticeira que usa os poderes da alma para seduzir, paralisar ou prejudicar. Contudo, a interpretação do Tarô sempre deu destaque ao seu lado alegre e prestativo. Ela representa uma das três cartas de 4 proteção e corresponde à interpretação da mitologia cristã, onde o herói é intocável sob a proteção da Virgem.',
        material: 'Avanço existente, mas lento, burocrático. Tarefas feitas com sinceridade e paciência.',
        mental: 'Profundidade, Planejamento, Momento de reflexão, Segredo, Pessoa que observa calada',
        sentimental: 'Compreensão, A profunda confiança. Afeição contida com sentimentos não revelados, como uma pessoa amistosa e receptiva, mas não afetuosa',
        espiritual: 'Momento de profundidade e imersão no inconsciente. Estado devocional propenso ao místico e as experiências espirituais. ',
        conselho: 'Mantenha a calma. Analize, observe e aguarde o momento certo de agir ser revelado. Mantenha-se à disposição e confie em sua voz interior.',
        advertencia: 'Momento mau influenciado pela fuga da realidade e pelo medo de viver. Sentimentos inseguros, fofocas, atitudes egoístas e superficiais, dissimulação e intenções secretas são potenciais neste momento.',
        cartaDoDia: '<i>Por Hajo Banzhaf,</i><br>Deixe que dia de hoje venha tranqüilamente ao seu encontro e observe, sem nenhuma intenção ou expectativa, que acontecerá. Deixe que os acontecimentos se desenrolem e só interfira neles quando a sua voz interior lhe disser que faça. Caso os seus afazeres permitam, observe hoje tranqüilamente que se passa em você, quando não está em atividade. O que passa por sua cabeça? Do que você sente necessidade subitamente? Não precisa para isso se obrigar a ficar parado; siga apenas os seus impulsos interiores. Você se surpreenderá com quão intenso e satisfatório será esse dia, aparentemente ocioso. Preste atenção aos seus sonhos em especial, pois eles podem lhe transmitir informações valiosas.',
    },
    {
        img: '<img src="../img/cartas/maiores/03.jpg">',
        numero: 'III',
        nome: 'A Imperatriz',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/04.jpg">',
        numero: 'IV',
        nome: 'O Imperador',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/05.jpg">',
        numero: 'V',
        nome: 'O Hierofante',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/06.jpg">',
        numero: 'VI',
        nome: 'O Enamorado',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/07.jpg">',
        numero: 'VII',
        nome: 'O Carro',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/11.jpg">',
        numero: 'VIII',
        nome: 'A Justiça',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/09.jpg">',
        numero: 'IX',
        nome: 'O Eremita',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/10.jpg">',
        numero: 'X',
        nome: 'A Roda da Fortuna',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/08.jpg">',
        numero: 'XI',
        nome: 'A Força',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/12.jpg">',
        numero: 'XII',
        nome: 'O Pendurado',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/13.jpg">',
        numero: 'XIII',
        nome: 'A Morte',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/14.jpg">',
        numero: 'XIV',
        nome: 'A Temperança',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/15.jpg">',
        numero: 'XV',
        nome: 'O Diabo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/16.jpg">',
        numero: 'XVI',
        nome: 'A Torre',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/17.jpg">',
        numero: 'XVII',
        nome: 'A Estrela',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/18.jpg">',
        numero: 'XVIII',
        nome: 'A Lua',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/19.jpg">',
        numero: 'XIX',
        nome: 'O Sol',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/20.jpg">',
        numero: 'XX',
        nome: 'O Julgamento',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/maiores/21.jpg">',
        numero: 'XXI',
        nome: 'O Mundo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c01.jpg">',
        numero: '23',
        nome: 'Ás de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c02.jpg">',
        numero: '24',
        nome: 'Dois de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c03.jpg">',
        numero: '25',
        nome: 'Três de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c04.jpg">',
        numero: '26',
        nome: 'Quatro de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c05.jpg">',
        numero: '27',
        nome: 'Cinco de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c06.jpg">',
        numero: '28',
        nome: 'Seis de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c07.jpg">',
        numero: '29',
        nome: 'Sete de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c08.jpg">',
        numero: '30',
        nome: 'Oito de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c09.jpg">',
        numero: '31',
        nome: 'Nove de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c10.jpg">',
        numero: '32',
        nome: 'Dez de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c14.jpg">',
        numero: '33',
        nome: 'Rei de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c13.jpg">',
        numero: '34',
        nome: 'Rainha de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c12.jpg">',
        numero: '35',
        nome: 'Cavaleiro de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/copas/c11.jpg">',
        numero: '36',
        nome: 'Princesa de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o01.jpg">',
        numero: '37',
        nome: 'Ás de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o02.jpg">',
        numero: '38',
        nome: 'Dois de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o03.jpg">',
        numero: '39',
        nome: 'Três de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o04.jpg">',
        numero: '40',
        nome: 'Quatro de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o05.jpg">',
        numero: '41',
        nome: 'Cinco de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o06.jpg">',
        numero: '42',
        nome: 'Seis de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o07.jpg">',
        numero: '43',
        nome: 'Sete de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o08.jpg">',
        numero: '44',
        nome: 'Oito de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o09.jpg">',
        numero: '45',
        nome: 'Nove de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o10.jpg">',
        numero: '46',
        nome: 'Dez de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o14.jpg">',
        numero: '47',
        nome: 'Rei de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o13.jpg">',
        numero: '48',
        nome: 'Rainha de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o12.jpg">',
        numero: '49',
        nome: 'Cavaleiro de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/ouros/o11.jpg">',
        numero: '50',
        nome: 'Princesa de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e01.jpg">',
        numero: '51',
        nome: 'Ás de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e02.jpg">',
        numero: '52',
        nome: 'Dois de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e03.jpg">',
        numero: '53',
        nome: 'Três de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e04.jpg">',
        numero: '54',
        nome: 'Quatro de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e05.jpg">',
        numero: '55',
        nome: 'Cinco de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e06.jpg">',
        numero: '56',
        nome: 'Seis de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e07.jpg">',
        numero: '57',
        nome: 'Sete de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e08.jpg">',
        numero: '58',
        nome: 'Oito de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e09.jpg">',
        numero: '59',
        nome: 'Nove de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e10.jpg">',
        numero: '60',
        nome: 'Dez de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e14.jpg">',
        numero: '61',
        nome: 'Rei de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e13.jpg">',
        numero: '62',
        nome: 'Rainha de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e12.jpg">',
        numero: '63',
        nome: 'Cavaleiro de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/espadas/e11.jpg">',
        numero: '64',
        nome: 'Princesa de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p01.jpg">',
        numero: '65',
        nome: 'Ás de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p02.jpg">',
        numero: '66',
        nome: 'Dois de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p03.jpg">',
        numero: '67',
        nome: 'Três de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p04.jpg">',
        numero: '68',
        nome: 'Quatro de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p05.jpg">',
        numero: '69',
        nome: 'Cinco de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p06.jpg">',
        numero: '70',
        nome: 'Seis de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p07.jpg">',
        numero: '71',
        nome: 'Sete de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p08.jpg">',
        numero: '72',
        nome: 'Oito de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p09.jpg">',
        numero: '73',
        nome: 'Nove de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p10.jpg">',
        numero: '74',
        nome: 'Dez de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p14.jpg">',
        numero: '75',
        nome: 'Rei de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p13.jpg">',
        numero: '76',
        nome: 'Rainha de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p12.jpg">',
        numero: '77',
        nome: 'Cavaleiro de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img: '<img src="../img/cartas/paus/p11.jpg">',
        numero: '78',
        nome: 'Princesa de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        geral: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    }
];

var valores = [{
        nome: "Um",
        numerologia: "Atividade, iniciativa, impulso produtivo, força criadora, Yang.",
        conceito: "O Ás carrega em si o potencial enaltecido da característica do naipe na sua forma mais bruta, é o ponto de partida para a sua"+
        "manifestação que alcançará sua maturidade conforme for se aprimorando nos demais arcanos numerados. Um potencial a ser explorado e desenvolvido.",
        abrangencia: "Ponto de início, potencial concentrado, centro, princípio e unidade.",
        aspecto: "Só o impulso que encontra um eco positivo pode frutificar, os outros desaparecem sem produzir resultados.",
        menores: "Uma boa chance, uma verdadeira possibilidade, porém sem garantia de realização.",
        ouros: "Realizar e cuidar",
        espadas: "Planejar e idealizar",
        copas: "Compartilhar e sentir",
        paus: "Iniciar e inspirar",
    },
    {
        nome: "Dois",
        numerologia: "Dualidade, polo oposto, o outro, disposição receptiva, passividade, reação, Yin.",
        conceito: "O dois suge a partir da unidade e nele ocorre a polaridade. Carrega em sia a característica do complementar, do diferencial e do oposto.",
        abrangencia: "O Outro, complemento, contraposição, diferencial e dualidade",
        aspecto: "As variedades da polaridade.",
        menores: "Unir, harmonizar, modificar, rivalizar.",
        ouros: "Equiparar e mensurar",
        espadas: "Confrontar e desafiar",
        copas: "Compartilhar e associar",
        paus: "Compreender e perceber",
    },
    {
        nome: "Três",
        numerologia: "O nascimento do novo a partir da uniao dos opostos, vitalidade, fertilidade, síntese, o Divino.",
        conceito: "A partir de três pontos é possível definir um plano triangular e consequentemente seus contornos. Aqui começamos a entender como é possível expandir.",
        abrangencia: "Equilíbrio, harmonia, tríade, diferenças, contorno e escala.",
        aspecto: "Uma base estável(um banquinho de três pernas não balança),fertilidade.",
        menores: "Desenvolvimento intenso sobre uma base estável.",
        ouros: "Expandir e parceria.",
        espadas: "Discórdia e diversidade.",
        copas: "Comemorar e aproveitar",
        paus: "Unir e cooperar",
    },
    {
        nome: "Quatro",
        numerologia: "Disciplina, estrutura,realidade, segurança, o terreno.",
        conceito: "A partir de 4 pontos é possível dar volume ao plano, definir um objeto tridimensional e as direções, com isso alcançamos a estabilidade nos planos de manifestação"+
        "Aqui começamos a estruturar e entender delimitações",
        abrangencia: "Forma, estrutura, mensurar, conter, limite, volume e estabilidade.",
        aspecto: "Limitação, firmeza, estrutura.",
        menores: "Estabilidade e solidez, com uma possível tendência para rigidez",
        ouros: "Conter e permanecer",
        espadas: "Aguardar e refletir",
        copas: "Apego e remorso",
        paus: "Conciliar e alinhar",
    },
    {
        nome: "Cinco",
        numerologia: "Quintessência, microcosmo, sentido, número que representa o ser humano, busca pelo supremo, também o número do pecado",
        conceito: "A partir de cinco pontos formamos a imagem de um pentagrama, que representa a própria manifestação da vida e da vontade"+
        "do ser evoluir. Essa vontade transforma o mundo ao seu redor.",
        abrangencia: "Vontade, modificar, tranformar e desafiar.",
        aspecto: "As crises fazem parte de todo crescimento e desenvolvimento profundo",
        menores: "Desafio, crise",
        ouros: "Desestabilização, afastamento",
        espadas: "Engano, desonra.",
        copas: "Arrependimento e desperdício",
        paus: "Determinação e esforço",
    },
    {
        nome: "Seis",
        numerologia: "Penetração recíproca e fusão insolúvel de opostos, amor, equilíbrio, harmonia, sexualidade.",
        conceito: "Com 6 pontos a imagem de uma estrela de seis pontas surge, um equilíbrio que reúne o aspecto masculino e feminino.",
        abrangencia: "Integração, equilíbrio harmônico, sensibilidade e domínio.",
        aspecto: "União bem-sucedida.",
        menores: "Sucesso, auxílio, união.",
        ouros: "Desenvlver e aprimorar",
        espadas: "Avaliar e entender",
        copas: "Recordar e nostalgia",
        paus: "Reconhecimentos e conquista",
    },
    {
        nome: "Sete",
        numerologia: "Totalidade que engloba o Divino (3) e o Terreno (4)",
        conceito: "O 7 representa o equilibrio harmônico(6) de consciência, somado ao potencial de manifestação(1)e a soma entre o easpecto divino(3) com o material"+
        "(4), trazendo um aspecto de co-criador da realidade. Aqui começamos a ampliar o estado de consciência.",
        abrangencia: "Co-criação, consciência e manifestação",
        aspecto: "Ponto final e momento de transição crítico ",
        menores: "Exaustão, crise, risco",
        ouros: "Progresso e crescimento",
        espadas: "Estratégia e risco",
        copas: "Utopie e sonhos",
        paus: "Superação e ousadia",
    },
    {
        nome: "Oito",
        numerologia: "Número do recomeço (7+1= uma oitava), da transformação e do renascimento (pia batismal octogonal), número intermediário (octógono) entre o Divino (círculo) e o Terreno (quadrado).",
        conceito: "O 8 é a representação de um quadrado duplo que traz o entendimento de uma nova dimensão dos planos de manifestação, uma nova compreensão sobre algo já conhecido."+
        "O infinito (lemniscata) é uma de suas representações que traz uma jornada do ir e vir. Aqui começamos a colocar em prática o que foi aprendido",
        abrangencia: "Revisão, regeneração e consciência maior.",
        aspecto: "Transformação e renovação.",
        menores: "Mudança, novo começo",
        ouros: "Aprendizado e perícia",
        espadas: "Conflito e limitação",
        copas: "Consequencia e responsabilização",
        paus: "Evolução e conclusão",
    },
    {
        nome: "Nove",
        numerologia: "Voltar-se para o interior, recolhimento antes de dar um passo para o novo.",
        conceito: "O 9 é a representação do '3 x 3', o ternário com sua harmonia multiplicada e sendo considerado o ápice da realização intelectual e espiritual. "+
        "O último número antes do retorno a unidade. Aqui reconhecemos o que foi feito e suas consequências.",
        abrangencia: "Realização, verdade e manifestação",
        aspecto: "Cristalização.",
        menores: "Concentração agradável ou problemática",
        ouros: "Habilidade e proficiência",
        espadas: "Desepero e incertezas",
        copas: "Renovação e solução",
        paus: "Hesitação e cautela",
    },
    {
        nome: "Dez",
        numerologia: "Número da ordem divina, da totalidade, soma dos numerais cardinais 1+2+3+4=10",
        conceito: "O 10 é o retorno a unidade com a característica de concretização e total manifestação. É o retorno, porém em um outro nível de escala."+
        "Aqui alcançamos um novo nível de compreensão para recomeçar em um novo patamar, um novo ciclo se abre a nossa frente.",
        abrangencia: "Término, concretização, realização e plenitude.",
        aspecto: "Abundância, o Todo",
        menores: "Soma, abundância",
        ouros: "Realização",
        espadas: "Finalização",
        copas: "Plenitude",
        paus: "Nova fase de vida",
    },
    {
        nome: "Princesa",
        numerologia: "Não há",
        conceito: "Curiosidade e disposição são os aspectos presentes nas princesas/pajens.",
        abrangencia: "Representam a pessoa mais jovem e imatura, sem uma direção clara.",
        aspecto: "Sensação | Infância",
        menores: "Princesas/Pajens representam a energia manifestando-se na personalidade em seu estado primário, pouco desenvolvido e bruto. Eles são as bases do naipe.",
        ouros: "Curiosidade, sempre em movimento, gosto por atividades práticas de montar e desmontar coisas, criar novos projetos e explorar novas habilidades, confiança, presença, calma.",
        espadas: "Observação, atenta, inteligência, esperteza, estratégia, discrição, distância, vaidade, direto e pensativo.",
        copas: "Atenciosa, carinhosa, amiga, meiga, empatia, cuidadosa, educada, sensibilidade, sonhadora, sincera e altruísta",
        paus: "Prestativa, honestidade, delicada, lealdade, visionária, inquieta, pró-ativa, buscadora, misteriosa, estudiosa",
    },
    {
        nome: "Cavaleiro",
        numerologia: "Não há",
        conceito: "O movimento e a coragem são os aspectos dos cavaleiros",
        abrangencia: "Representam a juventude e a energia em buscar experiências e desafios.",
        aspecto: "Intuição | Juventude",
        menores: "Cavaleiros personificam a energia do naipe se desenvolvendo a pleno vapor, com toda sua força. Representam a intensidade da energia do naipe crescendo.",
        ouros: "Lealdade, perceverança, habilidade, pró-atividade, esforço, clama, praticidade e atenciosidade.",
        espadas: "Idealismo, racionalidade, impaciência, comunicação, foco, sagacidade, direto.",
        copas: "Conselheiro, Bom ouvinte, mediação, criatividade, sonhador, impulsividade, mediação e empatia",
        paus: "Carisma, influência, autenticidade, lideranca, motivação, mente aberta, entusiasmo, otimismo, apaixonante, intrépido",
    },
    {
        nome: "Rainha",
        numerologia: "Não há",
        conceito: "Desenvolvimento, crescimento e cuidado são os aspectos presentes nas Rainhas",
        abrangencia: "Representam o aspecto feminino, a mulher adulta e madura.",
        aspecto: "Emoção | Idade adulta",
        menores: "Rainhas representam a energia já desenvolvida, de forma madura e profunda. São a energia do naipe amadurecida.",
        ouros: "Proteção, carinho, acolhimento, prosperidade,  independência, fertilidade, conforto, estabilidade e cuidado.",
        espadas: "Independência, inteligência, astúcia, justiça, crítica, honestidade, direção e experiência.",
        copas: "Empatia, sensitividade, amorosidade, emoção, conselho, maturidade emoional, intuição, introspecção, sonhadora.",
        paus: "Dedicação, popularidade, inspiração, generosidade, energia, amicicidade, criatividadde, independência, influência, sensualidade e otimismo.",
    },
    {
        nome: "Rei",
        numerologia: "Não há",
        conceito: "Domínio, autoridade e proteção são os aspectos presentes nos Reis.",
        abrangencia: "Representantes do aspecto masculino, do homem adulto e maduro.",
        aspecto: "Pensamento | Maturidade",
        menores: "Reis representam o completo desenvolvimento de uma energia. Eles são os reis do naipe, o estágio mais alto que eles podem alcançar em seu desenvolvimento.",
        ouros: "Conservadorismo, simplicidade, generosidade, providência, prosperidade, ambiciosidade, sucesso, praticidade, cinistesia.",
        espadas: "Austeridade, objetividade, inteligência, estratégia, foco, justiça, racionalidade, diplomacia, observacionismo.",
        copas: "Conselheiro, Bom ouvinte, mediação, criatividade, sonhador, calma, maturidade emocional, simpatia.",
        paus: "Carisma, influência, autenticidade, liderança, motivação, mente aberta, entusiamo, otimismo, apaixonante e intrépido.",
    },
]