var arcano = [
    {
        img:'<img src="../img/cartas/maiores/00.jpg">',
        numero: '0 | 22',
        nome: 'O Louco',
        verbo: 'Ousar',
        chaves: 'Inocência, Novos começos, Espírito livre',
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/01.jpg">',
        numero: 'I',
        nome: 'O Mago',
        verbo: 'Criar',
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/02.jpg">',
        numero: 'II',
        nome: 'A Sacerdotiza | A Alta Sacerdotiza',
        verbo: 'Analizar',
        chaves: 'Intuição, Inconsciente, Voz Interior, Paciência, Reserva, Resignação',
        hebraico: 'Gimmel',
        astrologia: 'A Lua - Inconsciente, ânimo, premonição, sonho, sagacidade',
        simbologia: 'A Mãe celestial, a donzela. Simboliza o ato de analizar e esperar pela hora certa de agir ',
        aspectos: '**Guia interior, sabedoria, intuição feminina, visões, fantasia, mistério, disposição passiva, ser guiado. A Sacerdotisa protege o portal do templo sagrado da alma humana, só permitirá a entrada de quem souber decifrar seu enigma: fidelidade e integridade. Esse  conjunto simbólico sugere que há uma grande força pessoal retida e que não será revelada facilmente, há um desejo passivo e muita elucubração. A análise e a intuição são por demais profundas nos fatores envolvidos, a busca do conhecimento é pela perfeição, os projetos e as relações são as mais passivas e corretas possíveis. A PAPISA representa nossas habilidades desconhecidas, nossa sensibilidade, nossa intenção e uma confiança inexplicável mas profundamente enraizada. Ela é a chave para a verdade misteriosa que foge à nossa compreensão lógica. Ela sabe que a verdade que pode ser expressa não é a verdade eterna. Seu lado luminoso é a expressão da paciência, da compreensão, da indulgência, da bondade, da disposição para perdoar e utilizar o poder das forças inconscientes para o bem dos outros - como auxiliadora, curadora ou vidente. Mas seu lado sombrio corresponde ao arquétipo da "irmã negra", a feiticeira que usa os poderes da alma para seduzir, paralisar ou prejudicar. Contudo, a interpretação do Tarô sempre deu destaque ao seu lado alegre e prestativo. Ela representa uma das três cartas de 4 proteção e corresponde à interpretação da mitologia cristã, onde o herói é intocável sob a proteção da Virgem.',
        material: 'Avanço existente, mas lento, burocrático. Tarefas feitas com sinceridade e paciência.',
        mental: 'Profundidade, Planejamento, Momento de reflexão, Segredo, Pessoa que observa calada',
        sentimental: 'Compreensão, A profunda confiança. Afeição contida com sentimentos não revelados, como uma pessoa amistosa e receptiva, mas não afetuosa',
        espiritual: 'Momento de profundidade e imersão no inconsciente. Estado devocional propenso ao místico e as experiências espirituais. ',
        conselho: 'Mantenha a calma. Analize, observe e aguarde o momento certo de agir ser revelado. Mantenha-se à disposição e confie em sua voz interior.',
        advertencia: 'Momento mau influenciado pela fuga da realidade e pelo medo de viver. Sentimentos inseguros, fofocas, atitudes egoístas e superficiais, dissimulação e intenções secretas são potenciais neste momento.',
        cartaDoDia: '<i>Por Hajo Banzhaf,</i><br>Deixe que dia de hoje venha tranqüilamente ao seu encontro e observe, sem nenhuma intenção ou expectativa, que acontecerá. Deixe que os acontecimentos se desenrolem e só interfira neles quando a sua voz interior lhe disser que faça. Caso os seus afazeres permitam, observe hoje tranqüilamente que se passa em você, quando não está em atividade. O que passa por sua cabeça? Do que você sente necessidade subitamente? Não precisa para isso se obrigar a ficar parado; siga apenas os seus impulsos interiores. Você se surpreenderá com quão intenso e satisfatório será esse dia, aparentemente ocioso. Preste atenção aos seus sonhos em especial, pois eles podem lhe transmitir informações valiosas.',
    },
    {
        img:'<img src="../img/cartas/maiores/03.jpg">',
        numero: 'III',
        nome: 'A Imperatriz',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/04.jpg">',
        numero: 'IV',
        nome: 'O Imperador',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/05.jpg">',
        numero: 'V',
        nome: 'O Hierofante',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/06.jpg">',
        numero: 'VI',
        nome: 'O Enamorado | Os Amantes',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/07.jpg">',
        numero: 'VII',
        nome: 'O Carro',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/11.jpg">',
        numero: 'VIII',
        nome: 'A Justiça',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/09.jpg">',
        numero: 'IX',
        nome: 'O Eremita',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/10.jpg">',
        numero: 'X',
        nome: 'A Roda da Fortuna',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/08.jpg">',
        numero: 'XI',
        nome: 'A Força',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/12.jpg">',
        numero: 'XII',
        nome: 'O Pendurado | O Enforcado',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/13.jpg">',
        numero: 'XIII',
        nome: 'A Morte',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/14.jpg">',
        numero: 'XIV',
        nome: 'A Temperança',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/15.jpg">',
        numero: 'XV',
        nome: 'O Diabo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/16.jpg">',
        numero: 'XVI',
        nome: 'A Torre | A Casa de Deus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/17.jpg">',
        numero: 'XVII',
        nome: 'A Estrela',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/18.jpg">',
        numero: 'XVIII',
        nome: 'A Lua',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/19.jpg">',
        numero: 'XIX',
        nome: 'O Sol',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/20.jpg">',
        numero: 'XX',
        nome: 'O Julgamento',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/maiores/21.jpg">',
        numero: 'XXI',
        nome: 'O Mundo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c01.jpg">',
        numero: '23',
        nome: 'Ás de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c02.jpg">',
        numero: '24',
        nome: 'Dois de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c03.jpg">',
        numero: '25',
        nome: 'Três de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c04.jpg">',
        numero: '26',
        nome: 'Quatro de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c05.jpg">',
        numero: '27',
        nome: 'Cinco de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c06.jpg">',
        numero: '28',
        nome: 'Seis de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c07.jpg">',
        numero: '29',
        nome: 'Sete de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c08.jpg">',
        numero: '30',
        nome: 'Oito de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c09.jpg">',
        numero: '31',
        nome: 'Nove de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c10.jpg">',
        numero: '32',
        nome: 'Dez de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c14.jpg">',
        numero: '33',
        nome: 'Rei de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c13.jpg">',
        numero: '34',
        nome: 'Rainha de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c12.jpg">',
        numero: '35',
        nome: 'Cavaleiro de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/copas/c11.jpg">',
        numero: '36',
        nome: 'Princesa de Copas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o01.jpg">',
        numero: '37',
        nome: 'Ás de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o02.jpg">',
        numero: '38',
        nome: 'Dois de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o03.jpg">',
        numero: '39',
        nome: 'Três de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o04.jpg">',
        numero: '40',
        nome: 'Quatro de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o05.jpg">',
        numero: '41',
        nome: 'Cinco de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o06.jpg">',
        numero: '42',
        nome: 'Seis de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o07.jpg">',
        numero: '43',
        nome: 'Sete de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o08.jpg">',
        numero: '44',
        nome: 'Oito de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o09.jpg">',
        numero: '45',
        nome: 'Nove de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o10.jpg">',
        numero: '46',
        nome: 'Dez de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o14.jpg">',
        numero: '47',
        nome: 'Rei de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o13.jpg">',
        numero: '48',
        nome: 'Rainha de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o12.jpg">',
        numero: '49',
        nome: 'Cavaleiro de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/ouros/o11.jpg">',
        numero: '50',
        nome: 'Princesa de Ouros',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e01.jpg">',
        numero: '51',
        nome: 'Ás de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e02.jpg">',
        numero: '52',
        nome: 'Dois de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e03.jpg">',
        numero: '53',
        nome: 'Três de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e04.jpg">',
        numero: '54',
        nome: 'Quatro de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e05.jpg">',
        numero: '55',
        nome: 'Cinco de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e06.jpg">',
        numero: '56',
        nome: 'Seis de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e07.jpg">',
        numero: '57',
        nome: 'Sete de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e08.jpg">',
        numero: '58',
        nome: 'Oito de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e09.jpg">',
        numero: '59',
        nome: 'Nove de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e10.jpg">',
        numero: '60',
        nome: 'Dez de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e14.jpg">',
        numero: '61',
        nome: 'Rei de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e13.jpg">',
        numero: '62',
        nome: 'Rainha de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e12.jpg">',
        numero: '63',
        nome: 'Cavaleiro de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/espadas/e11.jpg">',
        numero: '64',
        nome: 'Princesa de Espadas',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p01.jpg">',
        numero: '65',
        nome: 'Ás de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p02.jpg">',
        numero: '66',
        nome: 'Dois de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p03.jpg">',
        numero: '67',
        nome: 'Três de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p04.jpg">',
        numero: '68',
        nome: 'Quatro de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p05.jpg">',
        numero: '69',
        nome: 'Cinco de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p06.jpg">',
        numero: '70',
        nome: 'Seis de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p07.jpg">',
        numero: '71',
        nome: 'Sete de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p08.jpg">',
        numero: '72',
        nome: 'Oito de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p09.jpg">',
        numero: '73',
        nome: 'Nove de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p10.jpg">',
        numero: '74',
        nome: 'Dez de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p14.jpg">',
        numero: '75',
        nome: 'Rei de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'cavaleiro no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p13.jpg">',
        numero: '76',
        nome: 'Rainha de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p12.jpg">',
        numero: '77',
        nome: 'Cavaleiro de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: 'Príncipe no tarot de Crowley',
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        img:'<img src="../img/cartas/paus/p11.jpg">',
        numero: '78',
        nome: 'Princesa de Paus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    }
];
var qtd = arcano.length;
var cartas = 78;

console.log(arcano.length);
console.log(arcano[0]);
