var arcano = [
    {
        numero: 'Sem Número',
        nome: 'O Louco',
        verbo: 'Ousar',
        chaves: 'Inocência, Novos começos, Espírito livre',
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'I',
        nome: 'O Mago',
        verbo: 'Criar',
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'II',
        nome: 'A Sacerdotiza',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'III',
        nome: 'A Imperatriz',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'IV',
        nome: 'O Imperador',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'V',
        nome: 'O Hierofante',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VI',
        nome: 'O Enamorado | Os Amantes',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VII',
        nome: 'O Carro',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VIII',
        nome: 'A Justiça',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'IX',
        nome: 'O Eremita',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'X',
        nome: 'A Roda da Fortuna',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XI',
        nome: 'A Força',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XII',
        nome: 'O Pendurado | O Enforcado',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIII',
        nome: 'A Morte',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIV',
        nome: 'A Temperança',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XV',
        nome: 'O Diabo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVI',
        nome: 'A Torre | A Casa de Deus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVII',
        nome: 'A Estrela',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVIII',
        nome: 'A Lua',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIX',
        nome: 'O Sol',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XX',
        nome: 'O Julgamento',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XXI',
        nome: 'O Mundo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
];
var qtd = arcano.length;
var cartas = 22;



