var caminho = [
    {
        numero: '0 | 22',
        nome: 'O Louco',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'I',
        nome: 'O Mago',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'II',
        nome: 'A Sacerdotiza | A Papisa',
        casa1: '<b>A PAPISA</b> representa nossas habilidades desconhecidas, nossa sensibilidade, nossa intenção e uma confiança inexplicável mas profundamente enraizada. Ela é a chave para a verdade misteriosa que foge à nossa compreensão lógica. Ela sabe que a verdade que pode ser expressa não é a verdade eterna. Seu lado luminoso é a expressão da paciência, da compreensão, da indulgência, da bondade, da disposição para perdoar e utilizar o poder das forças inconscientes para o bem dos outros - como auxiliadora, curadora ou vidente. Mas seu lado sombrio corresponde ao arquétipo da "irmã negra", a feiticeira que usa os poderes da alma para seduzir, paralisar ou prejudicar. Contudo, a interpretação do Tarô sempre deu destaque ao seu lado alegre e prestativo. Ela representa uma das três cartas de 4 proteção e corresponde à interpretação da mitologia cristã, onde o herói é intocável sob a proteção da Virgem. <br><b>Na vida profissional</b>, a PAPISA mostra se a nossa esfera de ação corresponde aos temas desta carta - os campos da terapia e do esoterismo - ou então interpreta a postura que assumimos na nossa vida profissional. Ela significa que enfrentamos as tarefas diárias com paciência e sinceridade, aceitando novos impulsos e motivações que fazem com que a decisão final no campo profissional dependa da nossa voz interior. Quando vivenciamos essa postura de um modo bem consciente, sentimos que estamos sendo bem orientados. Mas quando ela escapa ao nosso controle, nosso comportamento para com os outros toma-se intratável, incerto ou até ameaçador. <br><b>No plano da consciência</b>, esta carta corresponde a uma época em que dirigimos nossa atenção para o inconsciente e para as imagens da alma, deixando-nos levar por fantasias e sonhos criativos ou mergulhando nos tesouros das profundezas para levantar o véu sob o qual a PAPISA esconde sua sabedoria oculta, a "antiga verdade" há muito existente, mas que sempre precisa ser redescoberta. Nessa jornada, nossa compreensão - já dualista - fracassa em separar o bem do mal. A "sabedoria de berço" abriga o segredo da polaridade onipresente 9ue nos permite encarar simultaneamente, com fascinação e espanto, a face da fsis branca e a face da Isis negra - sem sabermos se estamos encontrando o bem ou o mal, a força que cura ou a força que destrói. Esse ar~uétipo da feminilidade foi descrito, em todo o seu fasCÍnio e perigo, por autores como Rider Haggard e Gustav Meyrink. <br><b>No âmbito das relações pessoais</b>, a PAPISA mostra principalmente o seu lado luminoso. Representa a compreensão, a profunda inclinação, a proximidade, o parentesco da alma, a sensibilidade e a dedicação no relacionamento interpessoal, e também a certeza de que um laço invisível nos une ao parceiro. Nas épocas em que vivemos sozinhos, esta carta significa que assim encontramos a paz profunda ou que permanecemos pacientes e abertos para um novo contato, ouvindo somente a nossa voz interior, não nos deixando pressionar por  coisa alguma.',
        casa2: 'Você tem considerado o assunto com paciência e na expectativa de uma oportunidade favorável. Talvez ainda esteja indeciso sobre como prosseguir; talvez ainda aguarde um sinal bem nítido. Tente ver, através das cartas nos Lugares 1 e 7, se é chegada a hora de agir.',
        casa3: 'Você tem sido indulgente, condescendente, complacente e talvez compassivo e prestativo. Estava disposto a seguir um impulso, ou  aguardava que sua voz interior lhe dissesse o que fazer. Pode ser que tenha se esquivado de agir com responsabilidade; agora é convidado, pela carta no Lugar 6, a dar início à ação.',
        casa4: 'Você causou uma impressão passiva, bastante retraída, e demonstrou que a hora daação ainda não é chegada. Você agiu de um modo sensível, talvez até mediúnico, ou então desligado da realidade, ingênuo e disperso.',
        casa5: 'Mostre-se compreensivo, indulgente, condescendente e disposto a aguardar o desenvolvimento ulterior antes de reagir ou de tomar decisões importantes. Deixe claro que está contando com um desenvolvimento satisfatório, mas não apresse nada. Mostre suas habilidades mediúnicas ou suas forças duradouras e auxiliadoras.',
        casa6: 'Abra-se ao mundo do irracional. Preste atenção à sua sensibilidade e àquilo que sua intuição lhe inspira. Verificará que, com seu propósito, pode ver através dos outros e dará a si mesmo, de uma fonte inexplicável, uma certeza profunda. Confie em sua sensibilidade e deixe-se guiar apenas por ela.',
        casa7: 'Compreenda que, nesse assunto, você não pode forçar nada e que um vaivém febril só irá prejudicá-lo. Você necessita de paciência e disposição para que as coisas cresçam e venham na sua direção. Proceda com cuidado e aguarde até que uma voz interior lhe diga o que fazer.',
    },
    {
        numero: 'III',
        nome: 'A Imperatriz',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'IV',
        nome: 'O Imperador',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'V',
        nome: 'O Hierofante',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'VI',
        nome: 'O Enamorado | Os Amantes',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'VII',
        nome: 'O Carro',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'VIII',
        nome: 'A Justiça',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'IX',
        nome: 'O Eremita',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'X',
        nome: 'A Roda da Fortuna',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XI',
        nome: 'A Força',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XII',
        nome: 'O Pendurado | O Enforcado',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XIII',
        nome: 'A Morte',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XIV',
        nome: 'A Temperança',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XV',
        nome: 'O Diabo',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XVI',
        nome: 'A Torre | A Casa de Deus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XVII',
        nome: 'A Estrela',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XVIII',
        nome: 'A Lua',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XIX',
        nome: 'O Sol',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XX',
        nome: 'O Julgamento',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: 'XXI',
        nome: 'O Mundo',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '23',
        nome: 'Ás de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '24',
        nome: 'Dois de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '25',
        nome: 'Três de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '26',
        nome: 'Quatro de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '27',
        nome: 'Cinco de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '28',
        nome: 'Seis de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '29',
        nome: 'Sete de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '30',
        nome: 'Oito de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '31',
        nome: 'Nove de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '32',
        nome: 'Dez de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '33',
        nome: 'Rei de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '34',
        nome: 'Rainha de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '35',
        nome: 'Cavaleiro de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '36',
        nome: 'Princesa de Copas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '37',
        nome: 'Ás de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '38',
        nome: 'Dois de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '39',
        nome: 'Três de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '40',
        nome: 'Quatro de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '41',
        nome: 'Cinco de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '42',
        nome: 'Seis de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '43',
        nome: 'Sete de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '44',
        nome: 'Oito de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '45',
        nome: 'Nove de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '46',
        nome: 'Dez de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '47',
        nome: 'Rei de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '48',
        nome: 'Rainha de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '49',
        nome: 'Cavaleiro de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '50',
        nome: 'Princesa de Ouros',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '51',
        nome: 'Ás de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '52',
        nome: 'Dois de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '53',
        nome: 'Três de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '54',
        nome: 'Quatro de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '55',
        nome: 'Cinco de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '56',
        nome: 'Seis de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '57',
        nome: 'Sete de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '58',
        nome: 'Oito de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '59',
        nome: 'Nove de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '60',
        nome: 'Dez de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '61',
        nome: 'Rei de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '62',
        nome: 'Rainha de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '63',
        nome: 'Cavaleiro de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '64',
        nome: 'Princesa de Espadas',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '65',
        nome: 'Ás de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '66',
        nome: 'Dois de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '67',
        nome: 'Três de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '68',
        nome: 'Quatro de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '69',
        nome: 'Cinco de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '70',
        nome: 'Seis de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '71',
        nome: 'Sete de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '72',
        nome: 'Oito de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '73',
        nome: 'Nove de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '74',
        nome: 'Dez de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '75',
        nome: 'Rei de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '76',
        nome: 'Rainha de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '77',
        nome: 'Cavaleiro de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    },
    {
        numero: '78',
        nome: 'Princesa de Paus',
        casa1: false,
        casa2: false,
        casa3: false,
        casa4: false,
        casa5: false,
        casa6: false,
        casa7: false,
    }
];
var qtd = caminho.length;
var cartas = 78;


console.log('Número de arcanos:' + caminho.length);
console.log(caminho[2]);