var arcano = [
    {
        numero: 'Sem Número',
        nome: 'O Louco',
        verbo: 'Ousar',
        chaves: 'Inocência, Novos começos, Espírito livre',
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'I',
        nome: 'O Mago',
        verbo: 'Criar',
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'II',
        nome: 'A Sacerdotiza',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'III',
        nome: 'A Imperatriz',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'IV',
        nome: 'O Imperador',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'V',
        nome: 'O Hierofante',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VI',
        nome: 'O Enamorado | Os Amantes',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VII',
        nome: 'O Carro',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'VIII',
        nome: 'A Justiça',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'IX',
        nome: 'O Eremita',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'X',
        nome: 'A Roda da Fortuna',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XI',
        nome: 'A Força',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XII',
        nome: 'O Pendurado | O Enforcado',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIII',
        nome: 'A Morte',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIV',
        nome: 'A Temperança',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XV',
        nome: 'O Diabo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVI',
        nome: 'A Torre | A Casa de Deus',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVII',
        nome: 'A Estrela',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XVIII',
        nome: 'A Lua',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XIX',
        nome: 'O Sol',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
    {
        numero: 'XX',
        nome: 'O Julgamento',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false,
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,  
    },
    {
        numero: 'XXI',
        nome: 'O Mundo',
        verbo: false,
        chaves: false,
        hebraico: false,
        astrologia: false,
        simbologia: false,
        aspectos: false,
        material: false,
        mental: false,
        sentimental: false, 
        espiritual: false,
        conselho: false,
        advertencia: false,
        cartaDoDia: false,
    },
];
var qtd = arcano.length;

function getRandom() {
    var sorteado = document.getElementById('arcano');
    var referencia = document.getElementById('referencia');
    var simbologia = document.getElementById('simbologia');
    var aspectos =  document.getElementById('aspectos');
    var conselho = document.getElementById('conselho');
    var advertencia = document.getElementById('advertencia');
    var cartaDoDia = document.getElementById('cartaDoDia');
    var sorteia = Math.floor(Math.random() * qtd);
    sorteado.innerHTML = arcano[sorteia].numero + " - " + arcano[sorteia].nome;
    referencia.innerHTML = "<b>Verbo: </b>" + arcano[sorteia].verbo + "<br>" + "<b>Chaves: </b>" + arcano[sorteia].chaves + "<br>" + "<b>Letra Hebraica: </b>" + arcano[sorteia].hebraico + "<br>" + "<b>Astrologia: </b>" + arcano[sorteia].astrologia;
    simbologia.innerHTML = "<b>Simbologia:</b>"+arcano[sorteia].simbologia;
    aspectos.innerHTML = "<b>Aspectos gerais: </b>" + arcano[sorteia].aspectos + "<br>" + "<b>Material: </b>" + arcano[sorteia].material + "<br>" + "<b>Mental: </b>" + arcano[sorteia].mental + "<br>" + "<b>Sentimental: </b>" + arcano[sorteia].sentimental + "<br>" + "<b>Espiritual: </b>" + arcano[sorteia].espiritual;
    conselho.innerHTML = "<b>Conselho: </b>" + arcano[sorteia].conselho + "<br>" + "<b>Advertência: </b>" + arcano[sorteia].advertencia + "<br>" + "<b>Como carta do dia: </b>" + arcano[sorteia].cartaDoDia;
}

function getEscolha(){
    var escolhido = document.getElementById('arcano');
    var referencia = document.getElementById('referencia');
    var simbologia = document.getElementById('simbologia');
    var aspectos =  document.getElementById('aspectos');
    var conselho = document.getElementById('conselho');
    var advertencia = document.getElementById('advertencia');
    var cartaDoDia = document.getElementById('cartaDoDia');
    var select = document.getElementById('escolha');
    var escolha = select.options[select.selectedIndex].value;
    escolhido.innerHTML = arcano[escolha].numero + " - " + arcano[escolha].nome;
    referencia.innerHTML = "<b>Verbo: </b>" + arcano[escolha].verbo + "<br>" + "<b>Chaves: </b>" + arcano[escolha].chaves + "<br>" + "<b>Letra Hebraica: </b>" + arcano[escolha].hebraico + "<br>" + "<b>Astrologia: </b>" + arcano[escolha].astrologia;
    simbologia.innerHTML = "<b>Simbologia:</b>"+arcano[escolha].simbologia;
    aspectos.innerHTML = "<b>Aspectos gerais: </b>" + arcano[escolha].aspectos + "<br>" + "<b>Material: </b>" + arcano[escolha].material + "<br>" + "<b>Mental: </b>" + arcano[escolha].mental + "<br>" + "<b>Sentimental: </b>" + arcano[escolha].sentimental + "<br>" + "<b>Espiritual: </b>" + arcano[escolha].espiritual;
    conselho.innerHTML = "<b>Conselho: </b>" + arcano[escolha].conselho + "<br>" + "<b>Advertência: </b>" + arcano[escolha].advertencia + "<br>" + "<b>Como carta do dia: </b>" + arcano[escolha].cartaDoDia;

}

